---

- name: Ensure GPIO shutdown is properly configured
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtoverlay=gpio-shutdown'
    line: "dtoverlay=gpio-shutdown,gpio_pin={{ shutdown['button_gpio_pin'] }},gpio_pull=up,debounce={{ shutdown['debounce_ms'] }}"

- name: Ensure power LED is properly configured
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtparam=pwr_led_trigger='
    line: "dtparam=pwr_led_trigger=none,pwr_led_activelow=off"
